spring:
  application:
    name: download-manager-app
  rabbitmq:
    host: ${BROKER_HOST:172.16.232.4}
    port: ${BROKER_PORT:5672}
    username: ${BROKER_USERNAME:guest}
    password: ${BROKER_PASSWORD:guest}
    virtual-host: ${BROKER_VHOST:sda}
    ssl:
      enabled: ${BROKER_SSL:false}
      algorithm: TLSv1.2
      key-store: file:${KEYSTORE_PATH:/opt/certs/client/keystore.p12}
      key-store-type: ${KEYSTORE_TYPE:PKCS12}
      key-store-password: ${KEYSTORE_PASSWORD:changeit}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.16.232.2:5432/foam}
    password: ${DB_PASSWORD:biobank}
    username: ${DB_USERNAME:biobank}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

application:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173/}
  jwt:
    secret-key: ${JWT_SECRET_KEY:12341234123412341234123412341234123412341234123412341234123412341234123412341234123412341234123412341234}
    expiration: ${JWT_EXPIRATION:900000} # an 15 minutes in milliseconds
    refresh-token:
      expiration: ${JWT_REFRESH_TOKEN:10800000} # a day in milliseconds
  export-file:
    routing-key: ${EXPORT_FILE_ROUTING_KEY:outbox_export}

logging:
  level:
    org.springframework.security: ${SECURITY_LOGGING_LEVEL:error}
    org.springframework.web: ${WEB_LOGGING_LEVEL:error}