spring:
  rabbitmq:
    host: ${BROKER_HOST:172.16.232.4}
    port: ${BROKER_PORT:5672}
    username: ${BROKER_USERNAME:guest}
    password: ${BROKER_PASSWORD:guest}
    virtual-host: ${BROKER_VHOST:foam}
    listener:
      simple:
        prefetch: 1
    ssl:
      enabled: ${BROKER_SSL:false}
      algorithm: TLSv1.2
      key-store: file:${KEYSTORE_PATH}
      key-store-type: ${KEYSTORE_TYPE:JKS}
      key-store-password: ${KEYSTORE_PASSWORD}

outbox:
  type: ${OUTBOX_TYPE:posix}
  path: ${OUTBOX_PATH:src/test/resources/}

archive:
  type: ${ARCHIVE_TYPE:s3}
  path: ${ARCHIVE_PATH:fega-pl-archive}
  s3:
    endpoint: ${S3_ENDPOINTE:http://172.16.232.6:9000}
    accessKey: ${S3_ACCESS_KEY:UGZyRlqI4t0ZihtrdNUx}
    secretKey: ${S3_SECRET_KEY:3j95SSx27Tj3BIxvIXVdQNXKXiUv1jQKP02FSkUC}

crypt4gh:
  private-key-path: /home/kkochel/IdeaProjects/FOAM/c4gh-file-service/src/test/resources/server_c4gh.sec
  private-key-password-path: uxPFPxI4Oe4H5qJ1UO7kMCkvKgNHEzrX
