spring:
  application:
    name: sda-foam-integration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.16.239.2:5432/sda?ssl=true&sslmode=require&sslrootcert=/opt/certs/ca.crt&sslcert=/opt/certs/client/client.crt&sslkey=/opt/certs/client/client.pk8}
    password: ${DB_PASSWORD:biobank}
    username: ${DB_USERNAME:postgres}
  rabbitmq:
    host: ${BROKER_HOST:172.16.239.4}
    port: ${BROKER_PORT:5671}
    username: ${BROKER_USERNAME:guest}
    password: ${BROKER_PASSWORD:guest}
    virtual-host: ${BROKER_VHOST:sda}
    ssl:
      enabled: ${BROKER_SSL:true}
      algorithm: TLSv1.2
      key-store: file:${KEYSTORE_PATH:/opt/certs/client/keystore.p12}
      key-store-type: ${KEYSTORE_TYPE:PKCS12}
      key-store-password: ${KEYSTORE_PASSWORD:changeit}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  foam-dataset:
    routing-key: ${FOAM_ROUTING_KEY:foam_dataset}
