spring:
  rabbitmq:
    host: ${BROKER_HOST:172.16.237.4}
    port: ${BROKER_PORT:5672}
    username: ${BROKER_USERNAME:guest}
    password: ${BROKER_PASSWORD:guest}
    virtual-host: ${BROKER_VHOST:foam}
    ssl:
      enabled: ${BROKER_SSL:false}
      algorithm: TLSv1.2
      key-store: file:${KEYSTORE_PATH}
      key-store-type: ${KEYSTORE_TYPE:JKS}
      key-store-password: ${KEYSTORE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.16.237.2:5432/foam}
    password: ${DB_PASSWORD:biobank}
    username: ${DB_USERNAME:biobank}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  servlet:
    context-path: /api


