version: "3.9"
services:
  s3-archive:
    image: "quay.io/minio/minio:latest"
    container_name: "s3-archive"
    restart: "no"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: biobank
      MINIO_ROOT_PASSWORD: biobank123
    volumes:
      - "/opt/foam/archive:/data"
    command: server --console-address ":9001" /data
    networks:
      foam_net:
        ipv4_address: 172.16.232.6

  broker-sda:
    image: rabbitmq:3-management-alpine
    container_name: "broker-sda"
    networks:
      foam_net:
        ipv4_address: 172.16.232.4

  foam-db:
    image: postgres:15.2
    container_name: "foam-db"
    restart: always
    environment:
      POSTGRES_PASSWORD: biobank
      POSTGRES_USER: biobank
      POSTGRES_DB: foam
    networks:
      foam_net:
        ipv4_address: 172.16.232.2

networks:
  foam_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.232.0/24
