version: "3.9"
services:

  broker-sda:
    image: rabbitmq:3-management-alpine
    container_name: "broker-sda"
    networks:
      foam_net:
        ipv4_address: 172.16.237.4
  foam-db:
    image: postgres:15.2
    container_name: "foam-db"
    restart: always
    environment:
      POSTGRES_PASSWORD: biobank
      POSTGRES_USER: biobank
      POSTGRES_DB: foam
    networks:
      foam_net:
        ipv4_address: 172.16.237.2

networks:
  foam_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.237.0/24
